{% set version = "2.7" %}

package:
  name: flye
  version: {{ version }}

source:
  url: https://github.com/fenderglass/Flye/archive/flye.tar.gz
  sha256: c11bad0288079bdfd90e17de68fc3847a02d6b2a78cbeb7da5dc47a96c8351be

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - {{ compiler('cxx') }}
    - zlib
  host:
    - python
    - setuptools
    - zlib
  run:
    - python

test:
  commands:
    - flye -h | grep Assembly
    - python -c "import flye.tests.test_toy as t; t.main()"

about:
  home: https://github.com/fenderglass/Flye/
  license: BSD-3-Clause
  summary: Fast and accurate de novo assembler for single molecule sequencing reads
