{% set version = "2.7" %}

package:
  name: flye
  version: {{ version }}

source:
  url: https://github.com/fenderglass/Flye/archive/flye.tar.gz
  sha256: 5238358b81e4dcc064c7675c20cc5dfed174b9366cc947bbbb1299b322b0f124

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - zlib
  host:
    - python
    - zlib
  run:
    - python

test:
  commands:
    - flye -h | grep Assembly
    - python -c "import flye.tests.test_toy as t; t.main()"

about:
  home: https://github.com/fenderglass/Flye/
  license: BSD-3-Clause
  summary: Fast and accurate de novo assembler for single molecule sequencing reads
