{% set name = "singlem" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8fb65555d86301c55bef0f4722f6ae0d0bd974d2a04cbb71973b51dc0013655

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - smafa >=0.5.0
    - vsearch

#test:
#  imports:
#    - gtdbtk
#    - gtdbtk.biolib_lite
#    - gtdbtk.config
#    - gtdbtk.external
#    - gtdbtk.external.pypfam
#    - gtdbtk.external.pypfam.HMM
#    - gtdbtk.external.pypfam.Scan

about:
  home: https://github.com/wwood/singlem
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'

#extra:
#  skip-lints:
#    - should_be_noarch_python
#    - should_not_use_skip_python
