{% set name = "tobias" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03dbd2e31715bb402039222dbf71c3b83405a3fd095c0f8368942c1e39a07536

build:
  number: 0
  skip: True # [py27]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pysam
    - matplotlib-base >=2
    - scikit-learn
    - pandas
    - pypdf2
    - xlsxwriter
    - pyBigWig
    - moods
    - pybedtools
    - adjusttext
    - svist4get
    - gimmemotifs
    - xgboost >=0.71

test:
  commands:
    - "TOBIAS --help"

about:
  home: https://github.com/loosolab/TOBIAS/
  doc_url: https://github.com/loosolab/TOBIAS/wiki
  license: MIT
  summary: Transcription factor Occupancy prediction By Investigation of ATAC-seq Signal 
  description: |
    TOBIAS (Transcription factor Occupancy prediction By Investigation of ATAC-seq Signal) is a collection
    of command-line bioinformatics tools for performing footprinting analysis on ATAC-seq data. 

extra:
  recipe-maintainers:
    - msbentsen
    - jenzopr
